### ISSUE TITLE
Revert controls

### ISSUE THREAD

**Issue by LgoAlter** [dvlden/uw-pub#10]
**Describe the bug**

**To Reproduce**
3. See a problem

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. Chrome]
 - Version [e.g. 120.0.6099.71]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 8]
 - OS: [e.g. Android 14]
 - Browser [e.g. Chrome]
 - Version [e.g. 120.0.6099.71]

**Additional context**

**Comment by nnx0r** [comment]
Please fill in the description details. I have no ideas what you want.
