### ISSUE TITLE
Goes to 404 error page instead of actual repository

### ISSUE THREAD

**Issue by ghost** [dvlden/uw-pub#11]
Hey mate, thanks for fix everything works as should now, the small issue it seems i'm having is whenever I go to my app manager in phone browser and go to details click homepage for ultrawide, I get 404 error page instead of actual repository for ultrawide.

**Comment by nnx0r** [comment]
Hello @BurningDalylight and thank you for opening this issue.
I am unsure what "homepage" are you referring to? Can you send me a screenshot showing what that link is?

Kind regards!

**Comment by ghost** [comment]
Yeah, sure first go to addons manager (waterfox app same goes for firefox) 
![Screenshot_20240202-191118_Waterfox](https://github.com/dvlden/uw-pub/assets/155431995/a1a9770b-b90b-4841-b789-e50f851dc557)
Next App itself
![Screenshot_20240202-190858_Waterfox](https://github.com/dvlden/uw-pub/assets/155431995/9b6289d8-db99-4f0a-896b-3f15cccc8c8a)
Then the homepage
![Screenshot_20240202-190903_Waterfox](https://github.com/dvlden/uw-pub/assets/155431995/59350496-1f07-46ab-9fca-7e7fd682b17c)
Then when you press it goes like this instead of the actual repos
![Screenshot_20240202-191251_Waterfox](https://github.com/dvlden/uw-pub/assets/155431995/cf8d71e0-fbc8-4ff4-bd1b-dbf4cf98ad10)

**Comment by nnx0r** [comment]
Ahaa. I forgot to update links on Firefox store. Gotcha!
Thank you for the report. I added new url, which is [uw.wtf](http://uw.wtf) _(short of UltraWideo)_ and website is coming within the end of February.

Currently, it will just redirect to this public repository.

Much appreciated for reporting this! 🙌
