### ISSUE TITLE
No longer functions on UKTV Play

### ISSUE THREAD

**Issue by jrawle** [dvlden/uw-pub#12]
**Describe the bug**
UltraWideo no longer works when watching shows on UKTV Play with its built in fullscreen. Videos are not stretched/zoomed. Shortcuts do not function. This applies when using the fullscreen icon provided as part of the UKTV Player. If I right click the video and use Firefox's Full Screen option from the context menu, UW functions as expected.

**To Reproduce**
1. Go to www.uktvplay.co.uk and watch any of the old TV shows that are in 4:3 format
2. Click the square icon on the right hand end of the player navigation to enter full screen.
3. Video does not fill the screen. Sortcuts (both keyboard and Ctrl-scroll) do not work.
4. Exit full screen. Right-click video. Choose "Full Screen" from Firefox's context menu.
5. Video will now zoom to fill the screen. Shortcuts work (albeit without the overlay telling you which mode it is entering)

**Expected behavior**
UltraWideo should function when using UKTV Play's own full screen function, as it did before a recent update to their site.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 122

**Additional context**
Bug only appeared very recently following an update to the UKTV Play site.

**Comment by nnx0r** [comment]
What is this magical platform that has some kind of sourcery protection agains screenshots and screen recording? 

I just tried in Chrome and in Firefox too. It works fine for me. 
Unable to screen record it, so here's the recording with my phone, directly in Firefox.

- [x] Shortcuts functioning
- [x] Trackpad pinch functioning
- [x] Banner overlay is visible
- [x] Custom scaling

https://github.com/dvlden/uw-pub/assets/3460368/6d0a872f-1eab-40f5-9261-4eb1f921a1fb

---

Does the platform look identical on your end, or maybe they did not roll out new update for everyone? Let me know. 

P.S. The option "Choose "Full Screen" from Firefox's context menu.", sort of works. It's actually the opposite for me of what you wrote. In Firefox fullscreen from context menu, I do not get banner overlay, but everything else still works as expected.

**Comment by jrawle** [comment]
Thanks for taking the time to look into it! Sorry for not providing a video, although it's hard to show it not working. It literally does nothing once in full screen mode.

Maybe it's a Linux issue?

The behaviour you see with Firefox's context menu Full Screen is the same as for me. Everything works except the banner overlay. (Bizarrely, in this mode, it doesn't show ads; the film freezes and the sound of the ad plays without the pictures. This is what it did before they changed the player this week...)

I'm happy to accept it's my particular setup, if you can't reproduce it. At least I have a workaround. Thanks again!

**Comment by nnx0r** [comment]
No worries. Wish if I could be of a better help. 
Perhaps they made a mistake somewhere during this change (I'm not aware how it was in the past). But perhaps they will fix it in the future. I doubt it's the Linux problem, unless you had OS version update at the same time they did rebranding 🤷‍♂️ 

Can you confirm to me, does it work on some other platform - as supposed? So that we can completely exclude Linux being part of the problem?

**Comment by jrawle** [comment]
I don't use any other platform, sorry. I did notice that they only specify Chrome as being supported on Linux, despite Firefox being supported on both Windows and Mac. Perhaps it's related to that.

**Comment by nnx0r** [comment]
Oh interesting. I'll move this to discussion board, in case someone else who uses that platform on Linux, comes across the same problem.

Thank you for your assistance!
