### ISSUE TITLE
not working on youtube anymore 

### ISSUE THREAD

**Issue by iiiGerardoiii** [dvlden/uw-pub#31]
not working on youtube anymore. it was recently but stopped.

When pressing Alt+Shift+Z to cycle modes, the indicator pops up at the center of the screen, but the video size doesn't change.

Version: 3.3.1
Browser: Firefox 130.0 (64-bit)
OS: Windows 11

**Comment by nnx0r** [comment]
Cannot reproduce. Is the indicator circle green or red? Maybe you have paused the extension, that's why it doesn't apply anything to the video itself.

<img width="267" alt="Screenshot 2024-09-16 at 08 36 51" src="https://github.com/user-attachments/assets/cff7a8b7-2981-4980-ba0f-9a3cc0366fea">

**Comment by iiiGerardoiii** [comment]
oh man you're absolutely right, it was off for some reason, maybe I hit the Activity shortcut by accident. Apologies. I don't have the add-on button on my toolbar so I couldn't see the "OFF" indicator either.

I also didn't know the red dot indicator meant it was "paused", so when I saw the pop-up text and I was like "hey, the add-on is enabled and it ain't working". 

Maybe a smol text would've made it more obvious, u know, for dumb people like me. 
e.g: 
![Untitled23](https://github.com/user-attachments/assets/2d1c0f28-c955-42c4-a8f6-cc82ab6c8dc7)
