### ISSUE TITLE
Scrollbar Visible in Fullscreen Mode on SkyShowtime

### ISSUE THREAD

**Issue by bartpiskulla** [dvlden/uw-pub#32]
**Describe the bug**
When watching content on the streaming service SkyShowtime.com in fullscreen mode (tested in the Polish version, unsure if the issue exists in other versions), the scrollbar remains visible. This issue persists even when the UltraVideo browser extension is deactivated using the keyboard shortcut (Alt+Ctrl+X). The scrollbar only disappears after fully disabling the extension through the browser's extension management panel. The issue occurs in both Microsoft Edge and Google Chrome browsers. 

**To Reproduce**
1. Go to SkyShowtime.com.
2. Ensure the UltraVideo extension is active, but use the keyboard shortcut (Alt+Ctrl+X) to deactivate it.
3.  Start watching any video.
4. Enter fullscreen mode.
5. Notice that the scrollbar remains visible in fullscreen mode.
6. Fully disable the UltraVideo extension via the browser extension management panel and observe the scrollbar finally disappearing

**Expected behavior**
In fullscreen mode, the scrollbar should not be visible regardless of the status of the UltraVideo extension, especially when it is deactivated via a keyboard shortcut.

**Screenshots/Videos**
![Zrzut ekranu 2024-10-10 172709](https://github.com/user-attachments/assets/b3721392-559f-4295-b3d9-222ac6757b06)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge | Google Chrome
 - Version Edge 129.0.2792.79 | Chrome 129.0.6668.90

**Additional context**
The scrollbar does not appear on other streaming services, such as Netflix, Max, Prime Video, or Disney+, when the UltraVideo extension is active.

**Comment by nnx0r** [comment]
Thank you for report.
I was on a long vacation and couldn't see your issue submission. 

This is a paid platform that I do not have access to. If you can email me your credentials, so that I can investigate and fix the problem, that'd be great. (n.dvlden@gmail.com) 

I'd notify you when I am done, so you can change your password. Without the access, I am unable to look into the problem.

Keeping this open, until you respond.

**Comment by bartpiskulla** [comment]
I sent it to your inbox.

**Comment by nnx0r** [comment]
Appreciate it. Just fixed it and responded back.
Please let me know here or via email when you get the update by the browser, if the problem no longer exists.

**Comment by bartpiskulla** [comment]
Yesterday I tested the extension on version 3.3.3 and everything works fine now. Thank you very much for fixing this bug so quickly.

**Comment by nnx0r** [comment]
Appreciate the feedback! Thank you for the help!
