### ISSUE TITLE
Oled Monitor Burn in solution for 16:9 video

### ISSUE THREAD

**Issue by BakaPhoenix** [dvlden/uw-pub#34]
**Is your feature request related to a problem? Please describe.**
I have a QD-OLED ultrawide monitor and after less than a year i already have burn in becasue youtube videos running at 16:9 have pillaboxes.

**Describe the solution you'd like**
Basically i thought that to even out the degradation of the display we could have the video be decentered on one side instead on the center. Every time we start a video is displayed to one side or the other either random or in a round robin fashion.

**Describe alternatives you've considered**
Having the video filling the whole screen could be a fix too but i really don't like either solution to stretch or zoom to fill the screen and so far no one else implementing something like this

I would really appreciate if you could implement this feature.
Thanks

**Comment by BakaPhoenix** [comment]
I find out there is a plug it that add ambient lighting to videos, probably is a better solution that the one i proposed.
Thanks.

**Comment by nnx0r** [comment]
I'll close this in favour of #23 - that could help with this.

I haven't tested it thoroughly and I am unsure if it would work for all the platforms out there, so it requires a lot of testing and improvements.
