### ISSUE TITLE
mlb.com

### ISSUE THREAD

**Issue by gmulh** [dvlden/uw-pub#37]
Viewing some (but not all) videos on mlb.com in fullscreen will shift the video up off the top edge of screen so only the bottom ~1/3 to 1/2 is visible. UltraWideo can still apply its normal/upscale/stretch transformations to the video but video remains partially above the top of screen.

 - OS: Windows 11
 - Edge
 - 131.0.2903.86

I can reproduce this consistently when viewing the condensed game/highlight recap videos from the game schedule/results pages. Some of the videos posted to the front page do not exhibit this behavior and will correctly display the full video frame.

Disabling this extension corrects the problem of the video shifting off the top edge when using fullscreen mode but the embedded video player used on mlb.com does not handle ultrawide monitors. Its fullscreen mode will zoom to fill screen width which results in losing the top and bottom of the video (bad on 21:9, even worse on 32:9 monitor).

**Comment by nnx0r** [comment]
I will check this out today. I do have macOS only, so I'm hoping Edge will behave the same for me. Noted that highlights are free to watch, so that's good.

Will get back to you, once I have any feedback or hopefully a solution to this problem.

**Comment by nnx0r** [comment]
Figured it out, it's possible to fix. I will push an update tonight, but may take some time for Chrome Web Store to approve the release.

**Comment by gmulh** [comment]
Wow, excellent. Thanks for the quick response. Is version information visible within the extension settings? How would I determine it's been updated so I can test?

Thanks again

-gary
________________________________

**Comment by nnx0r** [comment]
You're welcome. Not really a fast response, but I'll take it. 
Yes, you can list all extensions in your browser, find the UltraWideo among them and it will show the version, same/similar to the screenshot (depending on the browser)


Screenshot from Chrome:
<img width="418" alt="Screenshot 2024-12-13 at 18 02 08" src="https://github.com/user-attachments/assets/41b7aab9-cd17-4bb3-8807-b09c30d2c099" />

[chrome://extensions/](chrome://extensions/)

As soon as it shows up **3.3.4** for you, try it out and let me know.

**Comment by gmulh** [comment]
Got it, see it under edge://extensions >UltraWideo >Detailed

Currently v3.3.3

Thank you

-gary

________________________________

**Comment by gmulh** [comment]
3.3.4 installed now, confirmed fix is working. Videos no longer shifted off top of screen. Thank you.

________________________________

**Comment by gmulh** [comment]
Now that baseball season is starting again I've been visiting mlb.com and have noticed that while the fixes you put into 3.3.4 are still working there are still some videos which exhibit the vertical shift issue.

All the videos posted inline in the scrolling main feed on the [mlb.com](mlb.com) frontpage and videos linked from the [MLB.TV video archives](https://www.mlb.com/live-stream-games) are working correctly in fullscreen mode on ultrawide displays. These were the sources I was using for testing back in December. But now that the new season has begun I've noticed videos linked under the individual game recaps (from the [Scores](https://www.mlb.com/scores) page) are still having the problem of shifting off the top of screen. I assume these have always been broken and were never fixed by the previous changes you made because when I was testing this back in December it was after the season ended and so there weren't new game recap videos being posted, I wasn't going to this page.

Specifically I'm talking about going to https://www.mlb.com/scores and then clicking on "Wrap" under the box score of any game. Then click on "Video" right above "Top Highlights". Any of the videos posted on this page still have the problem of being shifted off the top of screen.

It isn't a big deal, once I realized the videos linked from the MLB.TV archive work fine I just started using that page to watch this season's condensed game recaps, but I though you might like to know that parts of the mlb.com site are still "broken".

Also I see the changelog on your website says the current version is now 3.4.1, but the version posted on [Google's chrome extension page](https://chromewebstore.google.com/detail/ultrawideo/bfbnagnphiehemkdgmmficmjfddgfhpl?pli=1) is still 3.3.4. I noticed this when I saw my version is still 3.3.4 and I was trying to figure out why it hadn't updated to 3.4.0 or 3.4.1.

**Comment by nnx0r** [comment]
Hello again! 

I will check that today, but the fix will be delayed for release.

Yes, I am working on some additional features and rewriting some parts to make it easier for me to keep adding new things or fix existing ones.

That is why the changelog has 2 versions more than the actual release, because I am writing what I've been working on, but did not want to release anything just yet.

Probably two more changelog versions before I make a release and then I will merge all those changes into a single log for convenience. At the moment it's just for me to know what I worked on, because changelog page has been disabled for extension updates for now...

Thanks for the feedback, I'll make sure to fix this too!

**Comment by nnx0r** [comment]
Fixed. Expect it to work in the upcoming release.

**Comment by gmulh** [comment]
Very cool. It looks like my browser has the update because I see version 3.4.3 now. I'll test it later tonight.

I noticed something else recently too, not sure if this was a change to how the extension works or not but I don't remember it working this way before. When first loading the condensed game recap videos from the MLB.TV archive page the UltraWideo extension icon (on browser toolbar) would have a white background and I would have to click it and hit "refresh page" to get the extension to actually work. Again that's not something I remember having to do back in December when I first started using your extension. And its definitely not something I was doing when viewing the highlight videos accessed from the game "Wrap" page (my reason for re-opening this back in March). So perhaps the only reason the extension wasn't working for those videos was because I wasn't refreshing the page?

It wasn't until after I submitted this latest report (in March) that I realized, under the extension settings, I could grant UltraWideo permission to all mlb.com sites and now I don't have to refresh the page anymore. So if you actually discovered something that needed to be fixed that's great, I'm glad I helped you find and fix it. But I guess this is a long way of saying it might have just been user-error all along. 😄

**Comment by nnx0r** [comment]
I have no ideas how you managed to strip access to all websites to UltraWideo, but yes - that is indeed an user-error.

However in my case, I realised that their player is different for each page, so I made some changes to fix their player issues and let UW handle the rest.

3.4.4 is latest version that has been published today.

**Comment by gmulh** [comment]
Confirmed I now have 3.4.4 and the inline videos on the "wrap" play correctly in fullscreen now. Thanks again, great extension.
