### ISSUE TITLE
Basic and premium features 

### ISSUE THREAD

**Issue by trimechee** [dvlden/uw-pub#5]
Hello, thank you for the new manifest v3 version of the great Ultrawideo extension! 🥇 💯 

We hope the basic features will remain free and the free version can be financed for example by advertisements, for example displaying 3 or 4 non-intrusive ads each time Ultrawideo is used, and the premium features and advanced options will be paid  so people can test the great Ultrawideo and can make a donation to use the advanced premium features! Thank you again for this rare and exceptional extension!

**Comment by nnx0r** [comment]
Hello!
Current features of v3 will remain free forever.

Pro features will be subscription upgrade with low cost of $2.99 per year, to support me and future development.

Thank you for using UW!

**Comment by trimechee** [comment]
Ohhh awesome great wonderful news ! Thank you so much Mr @dvlden :) 🥇 💯
