### ISSUE TITLE
UltraWide doesn't work with www2.movieorca.com video player in phone android.

### ISSUE THREAD

**Issue by ghost** [dvlden/uw-pub#6]
Hi, it seems the ultrawide app doesn't work with movieorca more specificly with their video players, it only happens in phone android browser, i'm using firefox fork called waterfox, both for my computer and phone, the phone one is having problem with that, curiosly when I used your previous version, it worked flawlessly, now it doesn't work and I tried upscaling/streaching, but nothing works.

**Comment by nnx0r** [comment]
Hello and thank you for your report. 
It is very interesting. I tried using Firefox and Waterfox and the results are equal. 

The major difference between these versions is that the extension now uses Manifest v3. Firefox has some weird approaches with it and it's not equally compatible with Chrome's manifest implementation. 

They now require user's permission to access all websites, which on Desktop is simple to activate. _(there's a video tutorial that I posted)_

But on mobile version, when I go to permissions, it doesn't show anything. So it seems that Manifest v3 is not yet fully compatible with mobile Firefox/Waterfox.

Here's my flow:
- I open YouTube for example
- Then I need to open Addon UltraWideo and choose settings from popup
- Then go back on YouTube and put the video in full-screen
- This makes it apply the mode to the video, but nothing besides

Even tho it seems like by opening popup the Firefox allows its access on the previous tab, the shortcuts (touch) are still not working.

I will try to use Manifest v2 for Firefox, but keep the new changes and see how it behaves, but it sounds hard to maintain two versions. Alternatively, I'll try to deactivate v3 for Firefox mobile, until manifest v3 starts working properly.

---

Can you please confirm that this is not platform specific (movieorca)? But instead it doesn't work with any platform at all?

**Comment by ghost** [comment]
Probably, but you know it's not only happens with movieorca, but with aniwatch.to, fmovies, huramovies, but not with lookmovies2.to due to them having diffrent video player, ultrawide works fine with that website, the problem it seems with those websites is that use the same video player for media, like I said the previous version of ultrawide worked fine, but the current one is having problem finding that specific video player to apply it's fixes.

**Comment by nnx0r** [comment]
I was able to setup debugging tools needed for this. 
Turns out there was a bug with touch events and Firefox does not support MV3 on Android, so that's another one, as I expected.

I'll release a new version soon, but Firefox team may take up to 14 days for review. They became so slow. Not sure why my extension submission is not immediate.

**Comment by nnx0r** [comment]
Moving this to a more appropriate issue #7.
Thank you for the report @BurningDalylight. Much appreciated!
